#!/bin/bash

echo "================================================"
echo "  VERCEL ENVIRONMENT VARIABLES SETUP GUIDE"
echo "================================================"
echo ""
echo "Il tuo deploy sta fallendo perché le environment variables"
echo "non sono ancora configurate su Vercel."
echo ""
echo "Hai 2 opzioni per configurarle:"
echo ""
echo "================================================"
echo "OPZIONE 1: Via Dashboard Vercel (PIÙ FACILE) ⭐"
echo "================================================"
echo ""
echo "1. Vai su: https://vercel.com/dashboard"
echo "2. Seleziona il tuo progetto (maelstorm-api)"
echo "3. Vai su: Settings → Environment Variables"
echo ""
echo "4. Aggiungi queste 3 variabili:"
echo ""
echo "   Nome: NEXT_PUBLIC_SUPABASE_URL"
echo "   Valore: https://your-project.supabase.co"
echo "   Environments: Production, Preview, Development"
echo "   [Add]"
echo ""
echo "   Nome: NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   Valore: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "   Environments: Production, Preview, Development"
echo "   [Add]"
echo ""
echo "   Nome: SUPABASE_SERVICE_ROLE_KEY"
echo "   Valore: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "   Environments: Production, Preview, Development"
echo "   [Add]"
echo ""
echo "5. Dopo aver aggiunto tutte le variabili:"
echo "   - Vai su: Deployments"
echo "   - Click sui ⋯ del deployment più recente"
echo "   - Seleziona: Redeploy"
echo ""
echo "================================================"
echo "OPZIONE 2: Via CLI Vercel (PIÙ VELOCE)"
echo "================================================"
echo ""
echo "Se hai Vercel CLI installato, esegui questi comandi:"
echo ""
echo "# 1. Aggiungi Supabase URL"
echo "vercel env add NEXT_PUBLIC_SUPABASE_URL"
echo ""
echo "# Quando richiesto:"
echo "# What's the value? → https://your-project.supabase.co"
echo "# Add to which Environments? → Production, Preview, Development (seleziona tutti)"
echo ""
echo "# 2. Aggiungi Anon Key"
echo "vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo ""
echo "# What's the value? → eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "# Environments? → Production, Preview, Development"
echo ""
echo "# 3. Aggiungi Service Role Key"
echo "vercel env add SUPABASE_SERVICE_ROLE_KEY"
echo ""
echo "# What's the value? → eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "# Environments? → Production, Preview, Development"
echo ""
echo "# 4. Redeploy"
echo "vercel --prod"
echo ""
echo "================================================"
echo "DOVE TROVARE LE CREDENZIALI SUPABASE"
echo "================================================"
echo ""
echo "Se non hai ancora un progetto Supabase:"
echo ""
echo "1. Vai su: https://supabase.com"
echo "2. Sign up / Login"
echo "3. Create new project: 'maelstorm-rpg'"
echo "4. Attendi 2-3 minuti per la creazione"
echo ""
echo "5. Vai su: Settings → API"
echo "6. Copia questi valori:"
echo ""
echo "   Project URL:"
echo "   https://xxxxxxxxxxxxx.supabase.co"
echo ""
echo "   anon/public key:"
echo "   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4eHh4..."
echo ""
echo "   service_role key (⚠️ Segreto!):"
echo "   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4eHh4..."
echo ""
echo "7. Prima di usare l'API, esegui il database schema:"
echo "   - SQL Editor in Supabase Dashboard"
echo "   - Copia contenuto di: supabase/schema.sql"
echo "   - Incolla e Run"
echo ""
echo "================================================"
echo "VERIFICA CONFIGURAZIONE"
echo "================================================"
echo ""
echo "Dopo aver configurato le env vars e redeployato:"
echo ""
echo "# Controlla che le variabili siano state aggiunte"
echo "vercel env ls"
echo ""
echo "# Test l'API"
echo "curl https://your-project.vercel.app/api/game/races"
echo ""
echo "# Dovresti vedere JSON con 22 razze ✅"
echo ""
echo "================================================"
echo "RISOLUZIONE PROBLEMI"
echo "================================================"
echo ""
echo "❌ Errore: 'Secret does not exist'"
echo "   → Hai aggiornato vercel.json? (fatto!)"
echo "   → Hai aggiunto le env vars su Vercel? (da fare)"
echo ""
echo "❌ Errore: 'Database connection failed'"
echo "   → Verifica che le credenziali Supabase siano corrette"
echo "   → Verifica che il database schema sia stato eseguito"
echo ""
echo "❌ Errore: 'Build failed'"
echo "   → Controlla i logs su Vercel Dashboard → Deployments → Logs"
echo ""
echo "================================================"
echo "QUICK LINKS"
echo "================================================"
echo ""
echo "Vercel Dashboard: https://vercel.com/dashboard"
echo "Supabase Dashboard: https://app.supabase.com"
echo "Guida completa: VERCEL_DEPLOY_GUIDE.md"
echo ""
